PASSWORDS_DID_NOT_MATCH = "Passwords didn't match"
PROBLEMS_WITH_USER = 'Problems with user'
ROLE_CREATED = 'Role created'
ROLE_UPDATED = 'Role updated'
ROLE_DELETED = 'Role deleted'
USER_ALREADY_EXIST = 'User already exist'
INCORRECT_PASSWORD = 'Incorrect password'  # noqa: S105
CANT_UPDATE_USER = "Can't update user"
CANT_ADD_ROLE_TO_USER = "Can't add role to user"
CANT_DELETE_ROLE_FROM_USER = "Can't delete role from user"
WRONG_PARAMS = 'Wrong params'
USER_DONT_EXIST = 'User do not exists'
CANT_FIND_USER = "Can't find user"
BAD_REQUEST = 'Bad request'
CANT_FIND_ROLE = "Can't find role"
EMAIL_IS_NOT_CONFIRMED = 'EMAIL IS NOT CONFIRMED'
