"""partitions_of_logs

Revision ID: ace74b8b0f27
Revises: 8e5534c2d440
Create Date: 2022-07-22 16:14:46.047296

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = 'ace74b8b0f27'
down_revision = '8e5534c2d440'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """CREATE TABLE IF NOT EXISTS "logs_login" PARTITION OF "logs" FOR VALUES IN ('login')"""
    )
    op.execute(
        """CREATE TABLE IF NOT EXISTS "logs_logout" PARTITION OF "logs" FOR VALUES IN ('logout')"""
    )
    op.execute(
        """CREATE TABLE IF NOT EXISTS "logs_logout_everywhere" PARTITION OF "logs" FOR VALUES IN ('logout_everywhere')"""
    )
    op.execute(
        """CREATE TABLE IF NOT EXISTS "logs_other" PARTITION OF "logs" FOR VALUES IN ('other')"""
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("logs_login")
    op.drop_table("logs_logout")
    op.drop_table("logs_logout_everywhere")
    op.drop_table("logs_other")
    # ### end Alembic commands ###
