"""partitions_of_logs

Revision ID: ace74b8b0f27
Revises: 8e5534c2d440
Create Date: 2022-07-22 16:14:46.047296

"""

# flake8: noqa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'ace74b8b0f27'
down_revision = '8e5534c2d440'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """CREATE TABLE IF NOT EXISTS "logs_2022_07" PARTITION OF "logs" FOR VALUES FROM ('2022-07-01') TO ('2022-08-01')"""
    )
    op.execute(
        """CREATE TABLE IF NOT EXISTS "logs_2022_08" PARTITION OF "logs" FOR VALUES FROM ('2022-08-01') TO ('2022-09-01')"""
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("logs_2022_07")
    op.drop_table("logs_2022_08")
    # ### end Alembic commands ###
