services:
  mongodb:
    image: mongo:6.0.1
    restart: unless-stopped
    ports:
      - 27017:27017
  postgres:
    image: postgres:14.2
    volumes:
      - ./test_schema.sql:/docker-entrypoint-initdb.d/schema.sql
    env_file:
      - .env
    ports:
      - 5432:5432
