filebeat.inputs:
  - type: log
    enabled: true
    tags: [ nginx_async ]
    paths:
      - /var/log/nginx/*
    json:
      keys_under_root: true
      add_error_key: true

output.logstash:
  enabled: true
  hosts: [ "${LOGSTASH_HOST}:${LOGSTASH_PORT}" ]