# Generated by Django 3.2 on 2022-04-30 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20220428_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personfilmwork',
            name='role',
            field=models.TextField(choices=[('director', 'director'), ('actor', 'actor'), ('writer', 'writer')], verbose_name='role'),
        ),
    ]
