# Generated by Django 3.2 on 2022-06-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_indexes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='filmwork',
            index=models.Index(fields=['created'], name='film_work_created_6ebd1f_idx'),
        ),
        migrations.AddIndex(
            model_name='filmwork',
            index=models.Index(fields=['modified'], name='film_work_modifie_1a6953_idx'),
        ),
        migrations.AddIndex(
            model_name='genre',
            index=models.Index(fields=['created'], name='genre_created_375922_idx'),
        ),
        migrations.AddIndex(
            model_name='genre',
            index=models.Index(fields=['modified'], name='genre_modifie_148664_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['created'], name='person_created_dcebe2_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['modified'], name='person_modifie_471683_idx'),
        ),
    ]
